name: CI/CD Invoice App

on:
  push:
    branches:
    - feature/invoice_git_actions
  # worklow_dispatch:
  #   inputs:
  #     deploy

default:
  run:
    shell: bash
    working-directory: .

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  name: Build
  run-on: ubuntu-latest
  if: ${{ github.ref == 'refs/heads/feature/invoice_git_actions'}}
  steps:
    - name: Construir Aplicación
      uses: action/checkout@v4

    - name: Instalar Node
      uses: action/setup-node@v3
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install

    - name: Lins (EsLint)
      run: npm run lint

    - name: Construir artefacto/aplicación
      run: npm run build

    - name: Subir artefacto
      uses: action/upload_artifact@v3
        with:
          name: app-invoice-vite
          path: dist/