name: CI/CD Invoice App

on:
  push:
    branches:
    - feature/invoice_git_actions
  # worklow_dispatch:
  #   inputs:
  #     deploy

defaults:
  run:
    shell: bash
    working-directory: .

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Construir Aplicación
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Lins (EsLint)
        run: npm run lint

      - name: Construir artefacto/aplicación
        run: npm run build

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-invoice-vite
          path: dist/