name: CI/CD Invoice App

on:
  push:
    branches:
    - feature/invoice_git_actions
  # worklow_dispatch:
  #   inputs:
  #     deploy

defaults:
  run:
    shell: bash
    working-directory: .

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Construir Aplicación
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Lins (EsLint)
        run: npm run lint

      - name: Construir artefacto/aplicación
        run: npm run build

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-invoice-vite
          path: dist/
  deploy:
    needs: build
    name: Desplegar
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/head/feature/invoice_git_actions' }}

    steps:
        - name: Clonar repositorio
          uses: actions/checkout@v4

        - name: Bajar artefacto
          uses: actions/download-artifact@v4
          with:
            name: app-invoice-vite
          
        - run:  echo "Se descargo el artefacto"
        
        - name: Configurar GH Pages
          uses: actions/configure-pages@v5
        
        - run: echo "Se configuro configure-pages"

        - name: Subida a gh pages
          uses: actions/upload-pages-artifact@v3
          with:
            path: dist/

        - name: Despliegue de artefacto en GH Pages
          uses: actions/deploy-pages@v4