name: CI/CD Invoice App

on:
  push:
    branches:
    - feature/invoice_git_actions
  # workflow_dispatch


defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    timeout-minutes: 2
    name: Build
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest, windows-latest]
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    outputs:
      output1: ${{ steps.construir_artefacto.outputs.valor1}} #Hay que definir los id en cada step para que sean identificados y poder usar outputs
      output2: ${{ steps.imprimir_texto.outputs.valor2}} 
    env:
      mysecret: ${{ secrets.MY_TOKEN_AZURE_CLOUD }}
    steps:
      - name: Construir Aplicación
        id: clonar_repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        id: instalar_node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}

      - name: Instalar dependencias
        id: instalar_dependencias
        run: | 
          npm install
          echo "Dependencias instaladas"

      - name: Lins (EsLint)
        id: lint
        run: npm run lint

      - name: Construir artefacto/aplicación
        id: construir_artefacto
        run: |
          npm run build
          echo "Artefacto construido"
          echo "::debug::Artefacto construido!!"
          echo "### Artefacto Construido- ${{ matrix.os}} :rocket:" >> $GITHUB_STEP_SUMMARY 
          echo "action_state=yellow" >> "$GITHUB_ENV"
          echo "valor1= since_job1_step5" >> $GITHUB_OUTPUT

      - name: Subir artefacto
        id: subir_artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-invoice-vite-${{ matrix.os }}-node-${{ matrix.node-version}}
          path: dist/

      - name: Texto de impresión
        id: imprimir_texto
        if: ${{ env.mysecret != '' }}
        run: |
          echo "### Ejecutando impresiones en consola :rocket:" >>$GITHUB_STEP_SUMMARY
          echo $action_state
          echo "valor2= $action_state" >> $GITHUB_OUTPUT
          echo "El secreto es: $mysecret"

        
  deploy:
    needs: build
    name: Desplegar
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
        - name: Clonar repositorio
          uses: actions/checkout@v4

        - name: Bajar artefacto
          uses: actions/download-artifact@v4
          with:
            name: 
          
        - run:  echo "Se descargo el artefacto"

        - env:
            OUTPUT1: ${{ needs.build.outputs.output1}}
            OUTPUT2: ${{ needs.build.outputs.output2}}
          run: echo "$OUTPUT1 $OUTPUT2"
  call-actions:
    name: Probar acciones personales
    runs-on: ubuntu-latest
    steps:
      - name: Llamar javascript-action-example
        id: hello
        uses: Eusebio9494/javascript-action-example@v1.1
        with:
          who-to-greet: Eusebio Olvera
      
      # Use the output from the `hello` step
      - name: Get the output time form the action
        run: echo "The time was ${{ steps.hello.outputs.time }}"

       
        
        # - name: Configurar GH Pages
        #   uses: actions/configure-pages@v5
        
        # - run: echo "Se configuro configure-pages"

        # - name: Subida a gh pages
        #   uses: actions/upload-pages-artifact@v3
        #   with:
        #     path: dist/

        # - name: Despliegue de artefacto en GH Pages
        #   uses: actions/deploy-pages@v4
