name: CI With Matrix

on:
    push: 
        branches: [feature/invoice_git_actions]

jobs:
    call-deploy:
        strategy:
            matrix:
                node-version: [14,16]
                os: [ubuntu-latest, windows-latest]
            max-parallel: 2
        uses: ./.github/workflows/deploy.yml