name: CI With Matrix

on:
    push: 
        branches: [feature/invoice_git_actions_workflow_call]



jobs:
    call-deploy:
        concurrency: 
            group: deploy-${{ matrix.os}}-${{github.ref}}
            cancel-in-progress: true
        strategy:
            matrix:
                node-version: [20]
                os: [ubuntu-latest, windows-latest]
            max-parallel: 2
        uses: ./.github/workflows/deploy.yml
        with:
            node-version: ${{ matrix['node-version']}}
            os: ${{ matrix['os']}}
        secrets:
            mysecret: ${{ secrets.MY_TOKEN_AZURE_CLOUD }}